export enum Feature {
  HOME_PAGE = "Home Page",
  USER_MANAGEMENT = "User Management",
  EQUIPMENT_INVENTORY = "Equipment Inventory",
  PAYMENT_PROCESSING = "Payment Processing",
  REPORTING = "Reporting",
  NOTIFICATIONS = "Notifications",
  CREATE_USER = "Create User",
  DELETE_USER = "Delete User",
  UPDATE_EQUIPMENT_INVENTORY = "Update Equipment Inventory",
  PROCESS_PAYMENT = "Process Payment",
  VIEW_REPORTS = "View Reports",
  SEND_EMAIL_NOTIFICATIONS = "Send Email Notifications",
  PAGE_LOAD = "PAGE_LOAD",
  TITLE_VERIFICATION = "TITLE_VERIFICATION",
  NAVIGATION = "NAVIGATION",
  SEARCH = "SEARCH",
}
